### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by samo790** [khval/NallePuh#13]
Attached :-)

[NallePUH_ITA.zip](https://github.com/khval/NallePuh/files/9998217/NallePUH_ITA.zip)

**Comment by khval** [comment]
Thanks for the translation, you’re a bit early, things might change.

søn. 13. nov. 2022 kl. 22:07 skrev samo79 ***@***.***>:

**Comment by samo790** [comment]
Yeah i know :-)
Aniway, noted a small typo in the original .cd

GAD_TOGGLE_LED  (//)
Toggele led

(Toggele instead of Toggle)

**Comment by khval** [comment]
That one might get removed, no led’s, and filters in nallepuh.

man. 14. nov. 2022 kl. 13:18 skrev samo79 ***@***.***>:

**Comment by khval** [comment]
@samo790 You can do translation now.

**Comment by samo790** [comment]
Ok will do :-)
Just a question, what does it means this string?

win_about_msg
replace this text

**Comment by khval** [comment]
@samo790 
ignore that one, is not used.

**Comment by samo790** [comment]
Ok attached the new translation

[NallePUH_ITA.zip](https://github.com/khval/NallePuh/files/10032890/NallePUH_ITA.zip)
