### ISSUE TITLE
GUI freeze when "activate" on X5000 with EMU10K

### ISSUE THREAD

**Issue by billborsari** [khval/NallePuh#21]
On my X5000 when I select an audio mode, and press activate, the GUI freezes.  The Deactivate, test, and about buttons all show clicks but do not do anything.  Also, the Mode Id and Mode Info are not populated.  

Let me know how else I can help to debug this.

**Comment by khval** [comment]
I experience no lockup issues here, please download source, and compile 0.6 (pre), 
and retest, there is a test button bug in 0.5, that’s fixed.
