### ISSUE TITLE
use GA_ReadOnly,TRUE in strings gadgets

### ISSUE THREAD

**Issue by javierdlr** [khval/NallePuh#31]
Hi, instead of using GA_Disabled,TRUE in string gadgets maybe GA_ReadOnly,TRUE
As with GA_Disabled (as in v1.4) text inside string gadget can be barely be readable.

**Comment by khval** [comment]
its now done, thanks for the tip

**Comment by javierdlr** [comment]
BTW in "main" tab (AHI) you didn't change it to GA_ReadOnly,TRUE
