### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by javierdlr** [khval/NallePuh#32]
Hi spanish translation attached.
[NallePUH_ES.zip](https://github.com/khval/NallePuh/files/13167232/NallePUH_ES.zip)

BTW can the group title be localized too?

TiA

**Comment by khval** [comment]
not yet..

**Comment by khval** [comment]
Thanks for translation, its now pushed repo.

**Comment by khval** [comment]
Groups are now translatable.

**Comment by khval** [comment]
@[javierdlr]
can you update your translation, I’m think we close final version of nallepuh, sure some stuff can be fixed, but not necessary, and I better things to do.

**Comment by javierdlr** [comment]
[NallePUH_ES.zip](https://github.com/khval/NallePuh/files/13256445/NallePUH_ES.zip)

Done, attached. Great work mate!!!!

**Comment by khval** [comment]
thanks

**Comment by javierdlr** [comment]
BTW in "main" tab (AHI) you didn't change it to GA_ReadOnly,TRUE

**Comment by javierdlr** [comment]
..and updated spanihs translation
[NallePUH_ES.zip](https://github.com/khval/NallePuh/files/13673984/NallePUH_ES.zip)
