### ISSUE TITLE
Text Typo (part 3)

### ISSUE THREAD

**Issue by samo790** [khval/NallePuh#35]
Few typos found in 1.5 :-)

- follwing porgrams (following programs)
- startup sequene (startup sequence) --> catalog
- Controll Register (Control Register) --> catalog
- Ingore DSI error (Ignore DSI error) --> readme.txt
- ... about what to installl (about what to install) --> installer

**Comment by khval** [comment]
thanks

**Comment by samo790** [comment]
follwing porgrams (following programs) --> this one still on shell output when NallePUH will be opened

**Comment by khval** [comment]
Oh.... I see, that one, maybe it should be translatable too. Oh.... I see, that one, maybe it should be translatable too.
I don’t see that text, because I have installed the libs :-)

**Comment by samo790** [comment]
Yeah, would be nice if you can make them translable, but for now a simple text correction would be ok too :-)

**Comment by samo790** [comment]
Ah i see you finally added it, but the error still :-))

str_following_porgrams_will_crash (//)
following porgrams will crash
;
str_following_porgrams_uses_this_library (//)
following porgrams uses this library

Should be "programs" NOT "porgrams" :-))

**Comment by khval** [comment]
All done, closing case.
PS! One more string added to the language catalog.

**Comment by samo790** [comment]
Some more typos found in "not-working.md" doc :-)

- commone couses (common causes)
- repport (report)
- Simon the Scorcerer (Simon the Sorcerer)
- cooper screen i think (copper screen i think)
- use Matrix insted (use Matrix instead)
- locksup (locks up)
- qucikly (quickly)

**Comment by samo790** [comment]
Some more typos in not-working.md :-)

- recreations (recreation)
- know has a HD installable (known as HD installable)
- after while (after a while)
- insted (instead)
- LeChuck's Revange (LeChuck's Revenge)
- locksup quickly (locks up quickly)
- maybe a cooper (maybe a copper)
- locksup (locks up)
