### ISSUE TITLE
Updated italian for 1.6

### ISSUE THREAD

**Issue by samo790** [khval/NallePuh#36]
Attached italian translation for 1.6

[NallePUH_ITA.zip](https://github.com/khval/NallePuh/files/13256842/NallePUH_ITA.zip)

**Comment by samo790** [comment]
@khval 

In string: str_copyright_by

For my italian translation i manually added the version number of the program, in this simple way:

"NallePUH 1.6 (c) - 2001 Martin Blom <martin@blom.org>"

Perhaps in the future we may replaced it by a simple "variable" versioning instead?

Something like:

"NallePUH % (c) - 2001 Martin Blom <martin@blom.org>"

When % would be the current NallePUH version

**Comment by khval** [comment]
Perhaps.

**Comment by khval** [comment]
Some way does not make sense add version number, he does know of the latest version, and it was version he worked on.

**Comment by samo790** [comment]
Knowing exactly which version are currently used is convenient for the end user, generally this is what the about window is for

**Comment by khval** [comment]
Perhaps you can just put the version number in the heading of the about window
version number is already the heading of main program.

**Comment by samo790** [comment]
In general the version number is inserted in the about window (just after the program name) by maybe also adding a variable for the VERSION, and in the Workbench titlebar (perhaps together with its compilation date, but this is not always necessary)

**Comment by khval** [comment]
Feel something missing in readme, Stephan Rupprecht in 2004 had to do lot stuff make run on AmigaOS. Not sure about versions number I guess 0.5 but did 0.4 exist as well?

**Comment by khval** [comment]
0.7 , 0.8 , 0.9, 1.0 does not exist because “make reversion” does not like 0.x versions, and x.0 versions.

**Comment by samo790** [comment]
If i remember correctly the ancient 0.3 were availible on both 68k and OS4, the 68k were done by Martin Blom while the later OS4 port was done by Rupprecht...
Probably also 0.4 and 0.5 were done by Rupprecht, but only for OS4

**Comment by samo790** [comment]
0.6/0.7 were probably just internal beta releases, never released for the public

**Comment by khval** [comment]
0.6 is the first version, I released. then jumped to 1.1

**Comment by samo790** [comment]
Ah ok

**Comment by samo790** [comment]
Updated italian to the current (1.8 WIP) release

[NallePUH_ITA.zip](https://github.com/khval/NallePuh/files/13600739/NallePUH_ITA.zip)
