### ISSUE TITLE
Italian catalog fix (post 1.6)

### ISSUE THREAD

**Issue by samo790** [khval/NallePuh#40]
Attached a fixed version + a couple of post 1.6 new strings

[nallepuh_ita.zip](https://github.com/khval/NallePuh/files/13439885/nallepuh_ita.zip)

**Comment by khval** [comment]
You have more strings to translate now :-P

**Comment by samo790** [comment]
Yep :-)
I will update this ticket tomorrow!

**Comment by samo790** [comment]
Attached the updated version

[nallepuh_ita_24.11.2023.zip](https://github.com/khval/NallePuh/files/13461652/nallepuh_ita_24.11.2023.zip)

**Comment by khval** [comment]
Ok, closing case, as it’s pushed to repo.
