### ISSUE TITLE
Crashes when started

### ISSUE THREAD

**Issue by spektro** [khval/NallePuh#41]
NallePuh (version 1.6) crashes when started: Guru meditation 80000003.

[Crashlog_nallepuh.debug_2023-12-02_20-14-55.txt](https://github.com/khval/NallePuh/files/13537026/Crashlog_nallepuh.debug_2023-12-02_20-14-55.txt)

**Comment by khval** [comment]
From what I can read from the source code, it can be caused by an error message, using old function.

**Comment by khval** [comment]
I’m just going to close this issue for now, think its solved.
