### ISSUE TITLE
Text typos (part 4)

### ISSUE THREAD

**Issue by samo790** [khval/NallePuh#42]
- Norwagine  (Norwegian) --> README
- package change, tooltype settings disabled as default. (Package change, tooltype settings disabled as default.) --> README
- programs that intent (programs that intend) --> README
- timing and and provide (timing and provide) --> README
- Please repport (Please report) --> README
- You now enable or disable blitter. (You can now enabled or disabled blitter.) --> README
- ADKCON/ADKCONR is now handled correct. (ADKCON/ADKCONR is now handled correctly) --> README

-  Worning (Warning) --> does-not-need-nallepuh.md

- but after while there is some sound (but after a while there is some sound) --> not-working.md
- Use ScummVM insted or DOSBox (Use ScummVM instead or DOSBox) --> not-working.md

**Comment by khval** [comment]
Okay thanks, I have made the changes.
