### ISSUE TITLE
Create a nice reaction GUI

### ISSUE THREAD

**Issue by khval** [khval/NallePuh#6]
Recreating the GUI, is the easiest path, as a lot event loop is already written, we have the .cd file etc.

**Comment by khval** [comment]
NallePUH.res file gives some hints, how to design the GUI as it was.
NallePUH.h (contains the GUI defines) this file should be generated.
NallePUH.cd should be moved under a sub directory. (see Basilisk)

I think NallePUHstr.s gives some hints too why the gui was not made for PPC.

**Comment by khval** [comment]
GUI uses lots of WriteLong/WriteWord, we should replace that.

**Comment by Hypexed** [comment]
In [NallePUH.res](https://github.com/khval/NallePuh/blob/main/NallePUH.res) what is REDC?

I wonder how this file was built? It looks like a layout text file. Possibly this could be built from the components of the resource.library that didn't make it into OS4. I recall the resource.library was useful for building a GUI in OS3.5+. Unfortunately such a generically named.. err... OS resource was also confusing, since the OS had resources and it perhaps wasn't the best play on words. :-)

**Comment by Hypexed** [comment]
Also NallePUHstr.s is built by CatComp. A sign of the times it's in 68K ASM. Most of it is fine as it's just creating a binary file, similar to how a font was constructed, which was common. Problem is the ASM snippet on the end though it is small.

Could be ported to PPC ASM or C but then how is the binary integrated?

Obviously what's needed is what file is given to CatComp to build the locale, an OS4 native CatComp or newer replacement.

**Comment by khval** [comment]
@Hypexed 

NallePUH.res reminds me of some macos binary gui, thing. 

>but then how is the binary integrated?

I think it was simply linked in.

>Could be ported to PPC ASM or C

Easier to simply recreate the GUI part, some of the stuff does make sense anyway.

**Comment by Hypexed** [comment]
> NallePUH.res reminds me of some macos binary gui, thing.

It looks auto generated but useful,

> I think it was simply linked in.

Strange way to include a static structure.

> Easier to simply recreate the GUI part, some of the stuff does make sense anyway.

Or use CatComp again to produce a normal file like portable C source. 

https://wiki.amigaos.net/wiki/SDK_Developer_Tools#CatComp

**Comment by khval** [comment]
I do use CatComp to generate .h and .c files, but this are only for the
translation, not the GUI elements.

The thing missing is iconify, needs a bit of fixing, maybe the gui can need
some redesign, feel free to change it.

man. 14. nov. 2022 kl. 12:39 skrev Hypexed ***@***.***>:

**Comment by khval** [comment]
It’s like 10 hours difference between Australia and Norway, it's almost
impossible to get an merge conflict ;-)

man. 14. nov. 2022 kl. 13:11 skrev Kjetil Hvalstrand <
***@***.***>:

**Comment by khval** [comment]
I have redesigned the GUI, (too many buttons)..
